import { ImbuimentProtecaoEnum, Item, Protecao, ProtecaoEnum, SlotEnum, VocacaoEnum } from "./item.model";

export class VocacaoItens {
  static itens(): Item[] {
    let itens: Item[] = [];
    let id = 1;

    // Hand (Wands)
    itens.push(new Item(id++, "Moonsilver Channeler", "https://www.tibiawiki.com.br/images/a/a5/Moonsilver_Channeler.gif", [VocacaoEnum.Sorcerer], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Energy, 7)], 0));
    itens.push(new Item(id++, "Grand Sanguine Coil", "https://www.tibiawiki.com.br/images/0/08/Grand_Sanguine_Coil.gif", [VocacaoEnum.Sorcerer], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Earth, 7)], 0));
    itens.push(new Item(id++, "Sanguine Coil", "https://www.tibiawiki.com.br/images/7/7a/Sanguine_Coil.gif", [VocacaoEnum.Sorcerer], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Earth, 7)], 0));
    itens.push(new Item(id++, "Soultainter", "https://www.tibiawiki.com.br/images/6/6d/Soultainter.gif", [VocacaoEnum.Sorcerer], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Death, 12)], 0));
    itens.push(new Item(id++, "Falcon Wand", "https://www.tibiawiki.com.br/images/1/17/Falcon_Wand.gif", [VocacaoEnum.Sorcerer], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Fire, 8)], 0));
    itens.push(new Item(id++, "Eldritch Wand", "https://www.tibiawiki.com.br/images/b/b8/Eldritch_Wand.gif", [VocacaoEnum.Sorcerer], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Energy, 4)], 0));
    itens.push(new Item(id++, "Gilded Eldritch Wand", "https://www.tibiawiki.com.br/images/a/a0/Gilded_Eldritch_Wand.gif", [VocacaoEnum.Sorcerer], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Energy, 4)], 0));
    itens.push(new Item(id++, "Naga Wand", "https://www.tibiawiki.com.br/images/d/d2/Naga_Wand.gif", [VocacaoEnum.Sorcerer], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Ice, 4)], 0));
    itens.push(new Item(id++, "Jungle Wand", "https://www.tibiawiki.com.br/images/6/60/Jungle_Wand.gif", [VocacaoEnum.Sorcerer], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Ice, 3)], 0));
    itens.push(new Item(id++, "Crypt Bile", "https://www.tibiawiki.com.br/images/a/ae/Crypt_Bile.gif", [VocacaoEnum.Sorcerer], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Fire, 6)], 0));
    itens.push(new Item(id++, "Amber Wand", "https://www.tibiawiki.com.br/images/1/18/Amber_Wand.gif", [VocacaoEnum.Sorcerer], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Ice, 6)], 0));
    itens.push(new Item(id++, "Inferniarch Wand", "https://www.tibiawiki.com.br/images/9/95/Inferniarch_Wand.gif", [VocacaoEnum.Sorcerer], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Earth, 5)], 0));

    // Hand (Rods)
    itens.push(new Item(id++, "Grand Sanguine Rod", "https://www.tibiawiki.com.br/images/c/c9/Grand_Sanguine_Rod.gif", [VocacaoEnum.Druid], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Death, 7)], 0));
    itens.push(new Item(id++, "Sanguine Rod", "https://www.tibiawiki.com.br/images/a/ac/Sanguine_Rod.gif", [VocacaoEnum.Druid], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Death, 7)], 0));
    itens.push(new Item(id++, "Soulhexer", "https://www.tibiawiki.com.br/images/4/45/Soulhexer.gif", [VocacaoEnum.Druid], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Ice, 12)], 0));
    itens.push(new Item(id++, "Falcon Rod", "https://www.tibiawiki.com.br/images/6/61/Falcon_Rod.gif", [VocacaoEnum.Druid], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Energy, 8)], 0));
    itens.push(new Item(id++, "Eldritch Rod", "https://www.tibiawiki.com.br/images/b/bd/Eldritch_Rod.gif", [VocacaoEnum.Druid], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Earth, 4)], 0));
    itens.push(new Item(id++, "Gilded Eldritch Rod", "https://www.tibiawiki.com.br/images/e/e4/Gilded_Eldritch_Rod.gif", [VocacaoEnum.Druid], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Earth, 4)], 0));
    itens.push(new Item(id++, "Naga Rod", "https://www.tibiawiki.com.br/images/f/fa/Naga_Rod.gif", [VocacaoEnum.Druid], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Fire, 4)], 0));
    itens.push(new Item(id++, "Jungle Rod", "https://www.tibiawiki.com.br/images/a/ac/Jungle_Rod.gif", [VocacaoEnum.Druid], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Earth, 3)], 0));
    itens.push(new Item(id++, "Crypt Jaw", "https://www.tibiawiki.com.br/images/e/ea/Crypt_Jaw.gif", [VocacaoEnum.Druid], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Energy, 6)], 0));
    itens.push(new Item(id++, "Amber Rod", "https://www.tibiawiki.com.br/images/f/f3/Amber_Rod.gif", [VocacaoEnum.Druid], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Fire, 6)], 0));
    itens.push(new Item(id++, "Inferniarch Rod", "https://www.tibiawiki.com.br/images/7/7f/Inferniarch_Rod.gif", [VocacaoEnum.Druid], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Death, 5)], 0));

    // Hands (Wands / Rods)
    itens.push(new Item(id++, "Moonsilver Sceptre", "https://www.tibiawiki.com.br/images/3/39/Moonsilver_Sceptre.gif", [VocacaoEnum.Druid], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Earth, 7)], 0));
    itens.push(new Item(id++, "Deepling Fork", "https://www.tibiawiki.com.br/images/9/9d/Deepling_Fork.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Holy, 8)], 0));
    itens.push(new Item(id++, "Deepling Ceremonial Dagger", "https://www.tibiawiki.com.br/images/1/1b/Deepling_Ceremonial_Dagger.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Earth, 5)], 0));
    itens.push(new Item(id++, "Energized Limb", "https://www.tibiawiki.com.br/images/a/a7/Energized_Limb.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Energy, 10)], 0));

    // Hands (Axes)
    itens.push(new Item(id++, "Grand Sanguine Claws", "https://www.tibiawiki.com.br/images/3/38/Grand_Sanguine_Claws.gif", [VocacaoEnum.Monk], SlotEnum.Hand, 0, false, [], 0));
    itens.push(new Item(id++, "Falcon Battleaxe", "https://www.tibiawiki.com.br/images/1/16/Falcon_Battleaxe.gif", [VocacaoEnum.Knight], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Energy, 12)], 0))
    itens.push(new Item(id++, "Falcon Mace", "https://www.tibiawiki.com.br/images/4/48/Falcon_Mace.gif", [VocacaoEnum.Knight], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Energy, 7)], 0))
    itens.push(new Item(id++, "Falcon Longsword", "https://www.tibiawiki.com.br/images/4/42/Falcon_Longsword.gif", [VocacaoEnum.Knight], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Earth, 12)], 0))

    // Hands (Bows)
    itens.push(new Item(id++, "Moonsilver Bow", "https://www.tibiawiki.com.br/images/c/cf/Moonsilver_Bow.gif", [VocacaoEnum.Paladin], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Fire, 7)], 0));
    itens.push(new Item(id++, "Grand Sanguine Bow", "https://www.tibiawiki.com.br/images/3/3a/Grand_Sanguine_Bow.gif", [VocacaoEnum.Paladin], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Earth, 6)], 0))
    itens.push(new Item(id++, "Sanguine Bow", "https://www.tibiawiki.com.br/images/f/fd/Sanguine_Bow.gif", [VocacaoEnum.Paladin], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Earth, 6)], 0))
    itens.push(new Item(id++, "Crypt Spine", "https://www.tibiawiki.com.br/images/e/ed/Crypt_Spine.gif", [VocacaoEnum.Paladin], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Ice, 5)], 0))
    itens.push(new Item(id++, "Soulbleeder", "https://www.tibiawiki.com.br/images/d/d3/Soulbleeder.gif", [VocacaoEnum.Paladin], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Holy, 7)], 0))
    itens.push(new Item(id++, "Amber Bow", "https://www.tibiawiki.com.br/images/d/d3/Amber_Bow.gif", [VocacaoEnum.Paladin], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Energy, 5)], 0))
    itens.push(new Item(id++, "Falcon Bow", "https://www.tibiawiki.com.br/images/f/fc/Falcon_Bow.gif", [VocacaoEnum.Paladin], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Fire, 5)], 0))
    itens.push(new Item(id++, "Lion Longbow", "https://www.tibiawiki.com.br/images/a/a7/Lion_Longbow.gif", [VocacaoEnum.Paladin], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Ice, 5)], 0))
    itens.push(new Item(id++, "Bow of Cataclysm", "https://www.tibiawiki.com.br/images/1/1d/Bow_of_Cataclysm.gif", [VocacaoEnum.Paladin], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Death, 4)], 0))
    itens.push(new Item(id++, "Living Vine Bow", "https://www.tibiawiki.com.br/images/6/61/Living_Vine_Bow.gif", [VocacaoEnum.Paladin], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Earth, 4)], 0))

    // Hands (Crossbow)
    itens.push(new Item(id++, "Moonsilver Crossbow", "https://www.tibiawiki.com.br/images/7/70/Moonsilver_Crossbow.gif", [VocacaoEnum.Paladin], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Holy, 7)], 0));
    itens.push(new Item(id++, "Grand Sanguine Crossbow", "https://www.tibiawiki.com.br/images/3/38/Grand_Sanguine_Crossbow.gif", [VocacaoEnum.Paladin], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Fire, 6)], 0))
    itens.push(new Item(id++, "Sanguine Crossbow", "https://www.tibiawiki.com.br/images/b/b5/Sanguine_Crossbow.gif", [VocacaoEnum.Paladin], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Fire, 6)], 0))
    itens.push(new Item(id++, "Soulpiercer", "https://www.tibiawiki.com.br/images/8/88/Soulpiercer.gif", [VocacaoEnum.Paladin], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Death, 7)], 0))
    itens.push(new Item(id++, "Naga Crossbow", "https://www.tibiawiki.com.br/images/6/6d/Naga_Crossbow.gif", [VocacaoEnum.Paladin], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Earth, 4)], 0))
    itens.push(new Item(id++, "Amber Crossbow", "https://www.tibiawiki.com.br/images/a/ac/Amber_Crossbow.gif", [VocacaoEnum.Paladin], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Energy, 5)], 0))
    itens.push(new Item(id++, "Inferniarch Arbalest", "https://www.tibiawiki.com.br/images/e/e7/Inferniarch_Arbalest.gif", [VocacaoEnum.Paladin], SlotEnum.Hand, 0, false, [new Protecao(ProtecaoEnum.Ice, 4)], 0))

    // Helmets
    itens.push(new Item(id++, "Dark Vision Bandana", "https://www.tibiawiki.com.br/images/e/ea/Dark_Vision_Bandana.gif", [VocacaoEnum.Monk], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Energy, 4)], 0));
    itens.push(new Item(id++, "Demon Mengu", "https://www.tibiawiki.com.br/images/d/d5/Demon_Mengu.gif", [VocacaoEnum.Monk], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 2), new Protecao(ProtecaoEnum.Death, 6)], 0));
    itens.push(new Item(id++, "Enchanted Werewolf Helmet (Fist)", "https://www.tibiawiki.com.br/images/3/3f/Enchanted_Werewolf_Helmet_%28Fist%29.gif", [VocacaoEnum.Monk], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 4)], 0));
    itens.push(new Item(id++, "Ethereal Coned Hat", "https://www.tibiawiki.com.br/images/2/2d/Ethereal_Coned_Hat.gif", [VocacaoEnum.Monk], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 4), new Protecao(ProtecaoEnum.Fire, 8)], 0));
    itens.push(new Item(id++, "Jade Conical Hat", "https://www.tibiawiki.com.br/images/3/3e/Jade_Conical_Hat.gif", [VocacaoEnum.Monk], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Ice, 4)], 0));
    itens.push(new Item(id++, "Light Bandana", "https://www.tibiawiki.com.br/images/8/81/Light_Bandana.gif", [VocacaoEnum.Monk], SlotEnum.Helmet, 0, false, [], 0));
    itens.push(new Item(id++, "Moonsilver Strike Helm", "https://www.tibiawiki.com.br/images/b/bf/Moonsilver_Strike_Helm.gif", [VocacaoEnum.Monk], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 5), new Protecao(ProtecaoEnum.Earth, 8)], 0));
    itens.push(new Item(id++, "Norcferatu Bonehood", "https://www.tibiawiki.com.br/images/0/04/Norcferatu_Bonehood.gif", [VocacaoEnum.Monk], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 2), new Protecao(ProtecaoEnum.Ice, 5)], 0));
    itens.push(new Item(id++, "Coned Hat of Enlightenment", "https://www.tibiawiki.com.br/images/3/39/Coned_Hat_of_Enlightenment.gif", [VocacaoEnum.Monk], SlotEnum.Helmet, 0, false, [], 0));
    itens.push(new Item(id++, "Arboreal Crown", "https://www.tibiawiki.com.br/images/8/86/Arboreal_Crown.gif", [VocacaoEnum.Druid], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 2), new Protecao(ProtecaoEnum.Ice, 9)], 0));
    itens.push(new Item(id++, "Spiritthorn Helmet", "https://www.tibiawiki.com.br/images/3/3e/Spiritthorn_Helmet.gif", [VocacaoEnum.Knight], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 6), new Protecao(ProtecaoEnum.Energy, 10)], 0));
    itens.push(new Item(id++, "Alicorn Headguard", "https://www.tibiawiki.com.br/images/9/95/Alicorn_Headguard.gif", [VocacaoEnum.Paladin], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 5), new Protecao(ProtecaoEnum.Fire, 5), new Protecao(ProtecaoEnum.Earth, 5), new Protecao(ProtecaoEnum.Energy, 5), new Protecao(ProtecaoEnum.Ice, 5), new Protecao(ProtecaoEnum.Holy, 5), new Protecao(ProtecaoEnum.Death, 5)], 0));
    itens.push(new Item(id++, "Arcanomancer Regalia", "https://www.tibiawiki.com.br/images/b/b1/Arcanomancer_Regalia.gif", [VocacaoEnum.Sorcerer], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 3), new Protecao(ProtecaoEnum.Earth, 7)], 0));
    itens.push(new Item(id++, "Falcon Coif", "https://www.tibiawiki.com.br/images/b/b9/Falcon_Coif.gif", [VocacaoEnum.Knight, VocacaoEnum.Paladin], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 3), new Protecao(ProtecaoEnum.Fire, 10)], 0));
    itens.push(new Item(id++, "Falcon Circlet", "https://www.tibiawiki.com.br/images/6/65/Falcon_Circlet.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Fire, 9)], 0));
    itens.push(new Item(id++, "Stag Helmet", "https://www.tibiawiki.com.br/images/6/69/Stag_Helmet.gif", [VocacaoEnum.Sorcerer], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 2), new Protecao(ProtecaoEnum.Energy, 6)], 0));
    itens.push(new Item(id++, "Demonfang Mask", "https://www.tibiawiki.com.br/images/9/97/Demonfang_Mask.gif", [VocacaoEnum.Druid], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 2), new Protecao(ProtecaoEnum.Death, 5)], 0));
    itens.push(new Item(id++, "Dreadfire Headpiece", "https://www.tibiawiki.com.br/images/3/3d/Dreadfire_Headpiece.gif", [VocacaoEnum.Sorcerer], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 2), new Protecao(ProtecaoEnum.Death, 6)], 0));
    itens.push(new Item(id++, "Hellstalker Visor", "https://www.tibiawiki.com.br/images/6/60/Hellstalker_Visor.gif", [VocacaoEnum.Paladin], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 3), new Protecao(ProtecaoEnum.Death, 6)], 0));
    itens.push(new Item(id++, "Maliceforged Helmet", "https://www.tibiawiki.com.br/images/6/66/Maliceforged_Helmet.gif", [VocacaoEnum.Knight], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 3), new Protecao(ProtecaoEnum.Death, 6)], 0));
    itens.push(new Item(id++, "Norcferatu Skullguard", "https://www.tibiawiki.com.br/images/1/18/Norcferatu_Skullguard.gif", [VocacaoEnum.Paladin], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 3), new Protecao(ProtecaoEnum.Ice, 6)], 0));
    itens.push(new Item(id++, "Cobra Hood", "https://www.tibiawiki.com.br/images/5/5b/Cobra_Hood.gif", [VocacaoEnum.Knight], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 5)], 0));
    itens.push(new Item(id++, "Eldritch Hood", "https://www.tibiawiki.com.br/images/7/75/Eldritch_Hood.gif", [VocacaoEnum.Druid], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Earth, 7)], 0));
    itens.push(new Item(id++, "Antler-Horn Helmet", "https://www.tibiawiki.com.br/images/7/78/Antler-Horn_Helmet.gif", [VocacaoEnum.Knight], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 3), new Protecao(ProtecaoEnum.Ice, 7)], 0));
    itens.push(new Item(id++, "Eldritch Cowl", "https://www.tibiawiki.com.br/images/1/1c/Eldritch_Cowl.gif", [VocacaoEnum.Sorcerer], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Ice, 7)], 0));
    itens.push(new Item(id++, "Terra Helmet", "https://www.tibiawiki.com.br/images/a/af/Terra_Helmet.gif", [VocacaoEnum.Knight], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 5), new Protecao(ProtecaoEnum.Earth, 5)], 0));
    itens.push(new Item(id++, "Stoic Iks Casque", "https://www.tibiawiki.com.br/images/7/7c/Stoic_Iks_Casque.gif", [VocacaoEnum.Paladin], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 3), new Protecao(ProtecaoEnum.Energy, 6)], 0));
    itens.push(new Item(id++, "Stoic Iks Headpiece", "https://www.tibiawiki.com.br/images/1/18/Stoic_Iks_Headpiece.gif", [VocacaoEnum.Druid], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Death, 3)], 0));
    itens.push(new Item(id++, "Lion Spangenhelm", "https://www.tibiawiki.com.br/images/8/86/Lion_Spangenhelm.gif", [VocacaoEnum.Paladin], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 3), new Protecao(ProtecaoEnum.Earth, 5)], 0));
    itens.push(new Item(id++, "Galea Mortis", "https://www.tibiawiki.com.br/images/3/34/Galea_Mortis.gif", [VocacaoEnum.Sorcerer], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Death, 6), new Protecao(ProtecaoEnum.Holy, -3)], 0));
    itens.push(new Item(id++, "Gnome Helmet", "https://www.tibiawiki.com.br/images/9/97/Gnome_Helmet.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 3), new Protecao(ProtecaoEnum.Energy, 8), new Protecao(ProtecaoEnum.Ice, -2)], 0));
    itens.push(new Item(id++, "Dark Whispers", "https://www.tibiawiki.com.br/images/0/04/Dark_Whispers.gif", [VocacaoEnum.Paladin], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Ice, 3)], 0));
    itens.push(new Item(id++, "Prismatic Helmet", "https://www.tibiawiki.com.br/images/6/68/Prismatic_Helmet.gif", [VocacaoEnum.Knight], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 5)], 0));
    itens.push(new Item(id++, "Zaoan Helmet", "https://www.tibiawiki.com.br/images/2/2f/Zaoan_Helmet.gif", [VocacaoEnum.Knight, VocacaoEnum.Paladin], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Physical, 5)], 0));
    itens.push(new Item(id++, "Elite Draken Helmet", "https://www.tibiawiki.com.br/images/c/c6/Elite_Draken_Helmet.gif", [VocacaoEnum.Paladin], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.Death, 3)], 0));
    itens.push(new Item(id++, "Witch Hat", "https://www.tibiawiki.com.br/images/4/4b/Witch_Hat.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.Helmet, 0, false, [new Protecao(ProtecaoEnum.ManaDrain, 5)], 0));

    // Armors
    itens.push(new Item(id++, "Naga Tanko", "https://www.tibiawiki.com.br/images/b/bb/Naga_Tanko.gif", [VocacaoEnum.Monk], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Physical, 2), new Protecao(ProtecaoEnum.Fire, 6)], 0));
    itens.push(new Item(id++, "Stag Robe", "https://www.tibiawiki.com.br/images/b/bf/Stag_Robe.gif", [VocacaoEnum.Monk], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Physical, 4)], 0));
    itens.push(new Item(id++, "Merudri Battle Mail", "https://www.tibiawiki.com.br/images/1/12/Merudri_Battle_Mail.gif", [VocacaoEnum.Monk], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Earth, 10), new Protecao(ProtecaoEnum.Energy, -5)], 0));
    itens.push(new Item(id++, "Stoic Iks Robe", "https://www.tibiawiki.com.br/images/5/5a/Stoic_Iks_Robe.gif", [VocacaoEnum.Monk], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Physical, 2), new Protecao(ProtecaoEnum.Energy, 5)], 0));
    itens.push(new Item(id++, "Leaf Robe", "https://www.tibiawiki.com.br/images/1/14/Leaf_Robe.gif", [VocacaoEnum.Monk], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Earth, 8), new Protecao(ProtecaoEnum.Fire, -8)], 0));
    itens.push(new Item(id++, "Magma Robe", "https://www.tibiawiki.com.br/images/4/44/Magma_Robe.gif", [VocacaoEnum.Monk], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Fire, 8), new Protecao(ProtecaoEnum.Ice, -8)], 0));
    itens.push(new Item(id++, "Ice Robe", "https://www.tibiawiki.com.br/images/6/61/Ice_Robe.gif", [VocacaoEnum.Monk], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Ice, 8), new Protecao(ProtecaoEnum.Energy, -8)], 0));
    itens.push(new Item(id++, "Energy Robe", "https://www.tibiawiki.com.br/images/5/5d/Energy_Robe.gif", [VocacaoEnum.Monk], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Energy, 8), new Protecao(ProtecaoEnum.Earth, -8)], 0));
    itens.push(new Item(id++, "Death Oyoroi", "https://www.tibiawiki.com.br/images/6/6a/Death_Oyoroi.gif", [VocacaoEnum.Monk], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Death, 5)], 0));
    itens.push(new Item(id++, "Spirit Bind", "https://www.tibiawiki.com.br/images/2/29/Spirit_Bind.gif", [VocacaoEnum.Monk], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Energy, 5), new Protecao(ProtecaoEnum.Ice, -5)], 0));
    itens.push(new Item(id++, "Robe of Enlightenment", "https://www.tibiawiki.com.br/images/1/1d/Robe_of_Enlightenment.gif", [VocacaoEnum.Monk], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Ice, 4)], 0));
    itens.push(new Item(id++, "Gnomish Cuirass", "https://www.tibiawiki.com.br/images/0/05/Gnomish_Cuirass.gif", [VocacaoEnum.Monk], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Physical, 2)], 0));
    itens.push(new Item(id++, "Ghazbaran Oyoroi", "https://www.tibiawiki.com.br/images/5/51/Ghazbaran_Oyoroi.gif", [VocacaoEnum.Monk], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Energy, 7), new Protecao(ProtecaoEnum.Ice, -7)], 0));
    itens.push(new Item(id++, "Native Armor", "https://www.tibiawiki.com.br/images/5/5f/Native_Armor.gif", [VocacaoEnum.Monk], SlotEnum.Armor, 0, false, [], 0));
    itens.push(new Item(id++, "Zaoan Monk Robe", "https://www.tibiawiki.com.br/images/6/66/Zaoan_Monk_Robe.gif", [VocacaoEnum.Monk], SlotEnum.Armor, 0, false, [], 0));
    itens.push(new Item(id++, "Monk Robe", "https://www.tibiawiki.com.br/images/9/99/Monk_Robe.gif", [VocacaoEnum.Monk], SlotEnum.Armor, 0, false, [], 0));
    itens.push(new Item(id++, "Merudri Scale Mail", "https://www.tibiawiki.com.br/images/7/75/Merudri_Scale_Mail.gif", [VocacaoEnum.Monk], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Fire, 4)], 0));
    itens.push(new Item(id++, "Merudri Nanbando", "https://www.tibiawiki.com.br/images/e/e9/Merudri_Nanbando.gif", [VocacaoEnum.Monk], SlotEnum.Armor, 0, false, [], 0));
    itens.push(new Item(id++, "Soulshroud", "https://www.tibiawiki.com.br/images/f/f0/Soulshroud.gif", [VocacaoEnum.Druid], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Death, 10)], 1, [ImbuimentProtecaoEnum.Earth, ImbuimentProtecaoEnum.Energy, ImbuimentProtecaoEnum.Fire, ImbuimentProtecaoEnum.Holy, ImbuimentProtecaoEnum.Ice]));
    itens.push(new Item(id++, "Spiritthorn Armor", "https://www.tibiawiki.com.br/images/a/a8/Spiritthorn_Armor.gif", [VocacaoEnum.Knight], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Physical, 13)], 1, Item.allImbuiments()));
    itens.push(new Item(id++, "Soulshell", "https://www.tibiawiki.com.br/images/f/fd/Soulshell.gif", [VocacaoEnum.Paladin], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Physical, 3), new Protecao(ProtecaoEnum.Fire, 15)], 1, [ImbuimentProtecaoEnum.Death, ImbuimentProtecaoEnum.Earth, ImbuimentProtecaoEnum.Energy, ImbuimentProtecaoEnum.Holy, ImbuimentProtecaoEnum.Ice]));
    itens.push(new Item(id++, "Soulmantle", "https://www.tibiawiki.com.br/images/c/cb/Soulmantle.gif", [VocacaoEnum.Sorcerer], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Physical, 4)], 1, Item.allImbuiments()));
    itens.push(new Item(id++, "Stag Plate", "https://www.tibiawiki.com.br/images/9/9b/Stag_Plate.gif", [VocacaoEnum.Paladin], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Physical, 5), new Protecao(ProtecaoEnum.Ice, 8)], 2, Item.allImbuiments(ImbuimentProtecaoEnum.Ice)));
    itens.push(new Item(id++, "Arcane Dragon Robe", "https://www.tibiawiki.com.br/images/3/38/Arcane_Dragon_Robe.gif", [VocacaoEnum.Sorcerer], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Ice, 12), new Protecao(ProtecaoEnum.Fire, -6)], 1, [ImbuimentProtecaoEnum.Death, ImbuimentProtecaoEnum.Earth, ImbuimentProtecaoEnum.Energy, ImbuimentProtecaoEnum.Holy]));
    itens.push(new Item(id++, "Dauntless Dragon Scale Armor", "https://www.tibiawiki.com.br/images/5/5e/Dauntless_Dragon_Scale_Armor.gif", [VocacaoEnum.Knight], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Physical, 8)], 2, Item.allImbuiments()));
    itens.push(new Item(id++, "Midnight Tunic", "https://www.tibiawiki.com.br/images/5/5d/Midnight_Tunic.gif", [VocacaoEnum.Druid], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Physical, 3)], 0));
    itens.push(new Item(id++, "Falcon Plate", "https://www.tibiawiki.com.br/images/d/dc/Falcon_Plate.gif", [VocacaoEnum.Knight], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Physical, 12)], 1, Item.allImbuiments()));
    itens.push(new Item(id++, "Lion Plate", "https://www.tibiawiki.com.br/images/3/3e/Lion_Plate.gif", [VocacaoEnum.Knight], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Physical, 6)], 1, Item.allImbuiments()));
    itens.push(new Item(id++, "Unerring Dragon Scale Armor", "https://www.tibiawiki.com.br/images/b/bc/Unerring_Dragon_Scale_Armor.gif", [VocacaoEnum.Paladin], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Energy, 10), new Protecao(ProtecaoEnum.Earth, -5)], 2, [ImbuimentProtecaoEnum.Death, ImbuimentProtecaoEnum.Ice, ImbuimentProtecaoEnum.Holy]));
    itens.push(new Item(id++, "Mutated Skin Armor", "https://www.tibiawiki.com.br/images/7/73/Mutated_Skin_Armor.gif", [VocacaoEnum.Paladin], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Physical, 3), new Protecao(ProtecaoEnum.Earth, 8)], 1, [ImbuimentProtecaoEnum.Death, ImbuimentProtecaoEnum.Energy, ImbuimentProtecaoEnum.Fire, ImbuimentProtecaoEnum.Holy, ImbuimentProtecaoEnum.Ice]));
    itens.push(new Item(id++, "Dawnfire Sherwani", "https://www.tibiawiki.com.br/images/5/5d/Dawnfire_Sherwani.gif", [VocacaoEnum.Sorcerer], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Fire, 10), new Protecao(ProtecaoEnum.Earth, -2)], 0));
    itens.push(new Item(id++, "Eldritch Cuirass", "https://www.tibiawiki.com.br/images/2/2e/Eldritch_Cuirass.gif", [VocacaoEnum.Knight], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Physical, 10)], 1, Item.allImbuiments()));
    itens.push(new Item(id++, "Norcferatu Bloodhide", "https://www.tibiawiki.com.br/images/8/86/Norcferatu_Bloodhide.gif", [VocacaoEnum.Sorcerer], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Earth, 8)], 1, Item.allImbuiments(ImbuimentProtecaoEnum.Earth)));
    itens.push(new Item(id++, "Norcferatu Bonecloak", "https://www.tibiawiki.com.br/images/6/68/Norcferatu_Bonecloak.gif", [VocacaoEnum.Druid], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Ice, 8)], 1, Item.allImbuiments(ImbuimentProtecaoEnum.Ice)));
    itens.push(new Item(id++, "Norcferatu Tuskplate", "https://www.tibiawiki.com.br/images/4/4f/Norcferatu_Tuskplate.gif", [VocacaoEnum.Knight], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Physical, 4)], 1, Item.allImbuiments()));
    itens.push(new Item(id++, "Bear Skin", "https://www.tibiawiki.com.br/images/f/fc/Bear_Skin.gif", [VocacaoEnum.Druid], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Earth, 11), new Protecao(ProtecaoEnum.Fire, -2)], 0));
    itens.push(new Item(id++, "Ghost Chestplate", "https://www.tibiawiki.com.br/images/0/08/Ghost_Chestplate.gif", [VocacaoEnum.Paladin], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Physical, 3)], 1, Item.allImbuiments()));
    itens.push(new Item(id++, "Embrace of Nature", "https://www.tibiawiki.com.br/images/d/d9/Embrace_of_Nature.gif", [VocacaoEnum.Paladin], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Ice, 11), new Protecao(ProtecaoEnum.Energy, -3)], 0));
    itens.push(new Item(id++, "Toga Mortis", "https://www.tibiawiki.com.br/images/4/4a/Toga_Mortis.gif", [VocacaoEnum.Sorcerer], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Death, 6)], 0));
    itens.push(new Item(id++, "Gnome Armor", "https://www.tibiawiki.com.br/images/a/a8/Gnome_Armor.gif", [VocacaoEnum.Paladin], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Physical, 4), new Protecao(ProtecaoEnum.Energy, 8), new Protecao(ProtecaoEnum.Ice, -2)], 1, [ImbuimentProtecaoEnum.Death, ImbuimentProtecaoEnum.Earth, ImbuimentProtecaoEnum.Fire, ImbuimentProtecaoEnum.Holy]));
    itens.push(new Item(id++, "Ornate Chestplate", "https://www.tibiawiki.com.br/images/d/de/Ornate_Chestplate.gif", [VocacaoEnum.Knight], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Physical, 8)], 1, Item.allImbuiments()));
    itens.push(new Item(id++, "Dream Shroud", "https://www.tibiawiki.com.br/images/a/ad/Dream_Shroud.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Energy, 10)], 0));
    itens.push(new Item(id++, "Living Armor", "https://www.tibiawiki.com.br/images/c/c4/Living_Armor.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Earth, 12), new Protecao(ProtecaoEnum.Fire, -5)], 0));
    itens.push(new Item(id++, "Depth Lorica", "https://www.tibiawiki.com.br/images/2/29/Depth_Lorica.gif", [VocacaoEnum.Paladin], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Death, 5)], 1, [ImbuimentProtecaoEnum.Earth, ImbuimentProtecaoEnum.Energy, ImbuimentProtecaoEnum.Fire, ImbuimentProtecaoEnum.Holy, ImbuimentProtecaoEnum.Ice]));
    itens.push(new Item(id++, "Prismatic Armor", "https://www.tibiawiki.com.br/images/4/42/Prismatic_Armor.gif", [VocacaoEnum.Knight, VocacaoEnum.Paladin], SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Physical, 5)], 0));
    itens.push(new Item(id++, "Elite Draken Mail", "https://www.tibiawiki.com.br/images/2/28/Elite_Draken_Mail.gif", [VocacaoEnum.Knight, VocacaoEnum.Paladin], SlotEnum.Armor, 0, false, [], 1, Item.allImbuiments()));
    itens.push(new Item(id++, "Elven Mail", "https://www.tibiawiki.com.br/images/0/01/Elven_Mail.gif", this.allVocations(), SlotEnum.Armor, 0, false, [], 2, Item.allImbuiments()));
    itens.push(new Item(id++, "Dwarven Armor", "https://www.tibiawiki.com.br/images/2/2c/Dwarven_Armor.gif", this.allVocations(), SlotEnum.Armor, 0, false, [new Protecao(ProtecaoEnum.Physical, 5)], 1, Item.allImbuiments()));

    // Legs
    itens.push(new Item(id++, "Sanguine Trousers", "https://www.tibiawiki.com.br/images/6/6a/Sanguine_Trousers.gif", [VocacaoEnum.Monk], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Physical, 4), new Protecao(ProtecaoEnum.Energy, 8)], 0));
    itens.push(new Item(id++, "Norcferatu Fleshguards", "https://www.tibiawiki.com.br/images/9/9e/Norcferatu_Fleshguards.gif", [VocacaoEnum.Monk], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Death, 4)], 0));
    itens.push(new Item(id++, "Mutant Hide Trousers", "https://www.tibiawiki.com.br/images/d/dd/Mutant_Hide_Trousers.gif", [VocacaoEnum.Monk], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Physical, 2), new Protecao(ProtecaoEnum.Earth, 5)], 0));
    itens.push(new Item(id++, "Legs of Wisdom", "https://www.tibiawiki.com.br/images/1/1f/Legs_of_Wisdom.gif", [VocacaoEnum.Monk], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Energy, 3)], 0));
    itens.push(new Item(id++, "Legs of Enlightenment", "https://www.tibiawiki.com.br/images/2/24/Legs_of_Enlightenment.gif", [VocacaoEnum.Monk], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Earth, 3)], 0));
    itens.push(new Item(id++, "Jungle Survivor Legs", "https://www.tibiawiki.com.br/images/9/97/Jungle_Survivor_Legs.gif", [VocacaoEnum.Monk], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Fire, 4)], 0));
    itens.push(new Item(id++, "Jade Legs", "https://www.tibiawiki.com.br/images/1/1b/Jade_Legs.gif", [VocacaoEnum.Monk], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Ice, 4)], 0));
    itens.push(new Item(id++, "Sanguine Legs", "https://www.tibiawiki.com.br/images/4/43/Sanguine_Legs.gif", [VocacaoEnum.Knight], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Physical, 9), new Protecao(ProtecaoEnum.Death, 6)], 0));
    itens.push(new Item(id++, "Sanguine Greaves", "https://www.tibiawiki.com.br/images/0/01/Sanguine_Greaves.gif", [VocacaoEnum.Paladin], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Physical, 7), new Protecao(ProtecaoEnum.Energy, 9)], 0));
    itens.push(new Item(id++, "Soulstrider", "https://www.tibiawiki.com.br/images/2/27/Soulstrider.gif", [VocacaoEnum.Druid], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Fire, 10)], 0));
    itens.push(new Item(id++, "Soulshanks", "https://www.tibiawiki.com.br/images/d/d2/Soulshanks.gif", [VocacaoEnum.Sorcerer], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Death, 10)], 0));
    itens.push(new Item(id++, "Mutant Bone Kilt", "https://www.tibiawiki.com.br/images/0/01/Mutant_Bone_Kilt.gif", [VocacaoEnum.Druid], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Physical, 3)], 0));
    itens.push(new Item(id++, "Stage Legs", "https://www.tibiawiki.com.br/images/0/06/Stag_Legs.gif", [VocacaoEnum.Knight], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Physical, 7), new Protecao(ProtecaoEnum.Fire, 7)], 0));
    itens.push(new Item(id++, "Falcon Greaves", "https://www.tibiawiki.com.br/images/2/2c/Falcon_Greaves.gif", [VocacaoEnum.Knight, VocacaoEnum.Paladin], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Physical, 7), new Protecao(ProtecaoEnum.Ice, 7)], 0));
    itens.push(new Item(id++, "Dawnfire Pantaloons", "https://www.tibiawiki.com.br/images/b/bb/Dawnfire_Pantaloons.gif", [VocacaoEnum.Sorcerer], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Physical, 3)], 0));
    itens.push(new Item(id++, "Stitched Mutant Hide Legs", "https://www.tibiawiki.com.br/images/0/06/Stitched_Mutant_Hide_Legs.gif", [VocacaoEnum.Knight], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Physical, 5), new Protecao(ProtecaoEnum.Earth, 5)], 0));
    itens.push(new Item(id++, "Mutated Skin Legs", "https://www.tibiawiki.com.br/images/7/76/Mutated_Skin_Legs.gif", [VocacaoEnum.Paladin], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Physical, 5), new Protecao(ProtecaoEnum.Earth, 4)], 0));
    itens.push(new Item(id++, "Norcferatu Bloodstrider", "https://www.tibiawiki.com.br/images/6/6c/Norcferatu_Bloodstrider.gif", [VocacaoEnum.Druid], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Death, 4)], 0));
    itens.push(new Item(id++, "Norcferatu Thornwraps", "https://www.tibiawiki.com.br/images/5/56/Norcferatu_Thornwraps.gif", [VocacaoEnum.Paladin], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Physical, 4), new Protecao(ProtecaoEnum.Death, 4)], 0));
    itens.push(new Item(id++, "Midnight Sarong", "https://www.tibiawiki.com.br/images/5/58/Midnight_Sarong.gif", [VocacaoEnum.Druid], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Ice, 7)], 0));
    itens.push(new Item(id++, "Stoic Iks Culet", "https://www.tibiawiki.com.br/images/7/7d/Stoic_Iks_Culet.gif", [VocacaoEnum.Knight], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Physical, 4), new Protecao(ProtecaoEnum.Energy, 2)], 0));
    itens.push(new Item(id++, "Stoic Iks Faulds", "https://www.tibiawiki.com.br/images/f/f7/Stoic_Iks_Faulds.gif", [VocacaoEnum.Sorcerer], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Fire, 6)], 0));
    itens.push(new Item(id++, "Fabulous Legs", "https://www.tibiawiki.com.br/images/6/60/Fabulous_Legs.gif", [VocacaoEnum.Knight, VocacaoEnum.Paladin], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Physical, 4), new Protecao(ProtecaoEnum.Fire, 2)], 0));
    itens.push(new Item(id++, "Gnome Legs", "https://www.tibiawiki.com.br/images/0/04/Gnome_Legs.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Energy, 7), new Protecao(ProtecaoEnum.Ice, -2)], 0));
    itens.push(new Item(id++, "Ornate Legs", "https://www.tibiawiki.com.br/images/4/44/Ornate_Legs.gif", [VocacaoEnum.Knight], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Physical, 5)], 0));
    itens.push(new Item(id++, "Soulful Legs", "https://www.tibiawiki.com.br/images/d/d4/Soulful_Legs.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Holy, 8)], 0));
    itens.push(new Item(id++, "Bast Legs", "https://www.tibiawiki.com.br/images/2/25/Bast_Legs.gif", [VocacaoEnum.Paladin], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Energy, 4)], 0));
    itens.push(new Item(id++, "Prismatic Legs", "https://www.tibiawiki.com.br/images/4/44/Prismatic_Legs.gif", [VocacaoEnum.Paladin], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Physical, 3)], 0));
    itens.push(new Item(id++, "Gill Legs", "https://www.tibiawiki.com.br/images/a/a6/Gill_Legs.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Earth, 8), new Protecao(ProtecaoEnum.Fire, -8)], 0));
    itens.push(new Item(id++, "Exotic Legs", "https://www.tibiawiki.com.br/images/e/e0/Exotic_Legs.gif", [VocacaoEnum.Knight], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Physical, 4)], 0));
    itens.push(new Item(id++, "Depth Ocrea", "https://www.tibiawiki.com.br/images/5/56/Depth_Ocrea.gif", [VocacaoEnum.Sorcerer, VocacaoEnum.Druid], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.ManaDrain, 15)], 0));
    itens.push(new Item(id++, "Yalahari Leg Piece", "https://www.tibiawiki.com.br/images/8/86/Yalahari_Leg_Piece.gif", [VocacaoEnum.Paladin], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Death, 5)], 0));
    itens.push(new Item(id++, "Zaoan Legs", "https://www.tibiawiki.com.br/images/1/1a/Zaoan_Legs.gif", this.allVocations(), SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Physical, 2)], 0));
    itens.push(new Item(id++, "Icy Culottes", "https://www.tibiawiki.com.br/images/2/25/Icy_Culottes.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Ice, 8)], 0));
    itens.push(new Item(id++, "Dwarven Legs", "https://www.tibiawiki.com.br/images/3/34/Dwarven_Legs.gif", this.allVocations(), SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Physical, 3)], 0));
    itens.push(new Item(id++, "Magma Legs", "https://www.tibiawiki.com.br/images/3/3d/Magma_Legs.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Fire, 6), new Protecao(ProtecaoEnum.Ice, -6)], 0));
    itens.push(new Item(id++, "Terra Legs", "https://www.tibiawiki.com.br/images/4/43/Terra_Legs.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Earth, 6), new Protecao(ProtecaoEnum.Fire, -6)], 0));
    itens.push(new Item(id++, "Glacier Kilt", "https://www.tibiawiki.com.br/images/e/e7/Glacier_Kilt.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Ice, 6), new Protecao(ProtecaoEnum.Energy, -6)], 0));
    itens.push(new Item(id++, "Lightning Legs", "https://www.tibiawiki.com.br/images/a/a2/Lightning_Legs.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.Legs, 0, false, [new Protecao(ProtecaoEnum.Energy, 6), new Protecao(ProtecaoEnum.Earth, -6)], 0));

    // Boots
    itens.push(new Item(id++, "Yalahari Footwraps", "https://www.tibiawiki.com.br/images/4/4d/Yalahari_Footwraps.gif", [VocacaoEnum.Monk], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Death, 3)], 0));
    itens.push(new Item(id++, "Stag Footwraps", "https://www.tibiawiki.com.br/images/6/6b/Stag_Footwraps.gif", [VocacaoEnum.Monk], SlotEnum.Boots, 0, false, [], 0));
    itens.push(new Item(id++, "Soulsoles", "https://www.tibiawiki.com.br/images/a/ae/Soulsoles.gif", [VocacaoEnum.Monk], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Physical, 3), new Protecao(ProtecaoEnum.Ice, 6)], 0));
    itens.push(new Item(id++, "Iks Footwraps", "https://www.tibiawiki.com.br/images/f/f8/Iks_Footwraps.gif", [VocacaoEnum.Monk], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Fire, 4)], 0));
    itens.push(new Item(id++, "Gnomish Footwraps", "https://www.tibiawiki.com.br/images/7/75/Gnomish_Footwraps.gif", [VocacaoEnum.Monk], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Physical, 2), new Protecao(ProtecaoEnum.Earth, 3)], 0));
    itens.push(new Item(id++, "Eldritch Monk Boots", "https://www.tibiawiki.com.br/images/0/05/Eldritch_Monk_Boots.gif", [VocacaoEnum.Monk], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Energy, 5)], 0));
    itens.push(new Item(id++, "Boots of Enlightenment", "https://www.tibiawiki.com.br/images/3/3f/Boots_of_Enlightenment.gif", [VocacaoEnum.Monk], SlotEnum.Boots, 0, false, [], 0));


    itens.push(new Item(id++, "Sanguine Galoshes", "https://www.tibiawiki.com.br/images/5/55/Sanguine_Galoshes.gif", [VocacaoEnum.Druid], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Physical, 2), new Protecao(ProtecaoEnum.Fire, 8)], 0));
    itens.push(new Item(id++, "Sanguine Boots", "https://www.tibiawiki.com.br/images/9/92/Sanguine_Boots.gif", [VocacaoEnum.Sorcerer], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Physical, 2), new Protecao(ProtecaoEnum.Ice, 8)], 0));
    itens.push(new Item(id++, "Pair of Soulwalkers", "https://www.tibiawiki.com.br/images/3/33/Pair_of_Soulwalkers.gif", [VocacaoEnum.Knight], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Physical, 7), new Protecao(ProtecaoEnum.Fire, 5)], 0));
    itens.push(new Item(id++, "Pair of Soulstalkers", "https://www.tibiawiki.com.br/images/c/cb/Pair_of_Soulstalkers.gif", [VocacaoEnum.Paladin], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Physical, 5)], 0));
    itens.push(new Item(id++, "Stag Boots", "https://www.tibiawiki.com.br/images/2/2a/Stag_Boots.gif", [VocacaoEnum.Druid], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Energy, 8)], 0));
    itens.push(new Item(id++, "Stag Shinguards", "https://www.tibiawiki.com.br/images/b/b9/Stag_Shinguards.gif", [VocacaoEnum.Paladin], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Physical, 2), new Protecao(ProtecaoEnum.Energy, 5)], 0));
    itens.push(new Item(id++, "Frostflower Boots", "https://www.tibiawiki.com.br/images/b/b8/Frostflower_Boots.gif", [VocacaoEnum.Knight], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Physical, 5), new Protecao(ProtecaoEnum.Ice, 5)], 0));
    itens.push(new Item(id++, "Feverbloom Boots", "https://www.tibiawiki.com.br/images/b/bb/Feverbloom_Boots.gif", [VocacaoEnum.Paladin], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Ice, 7)], 0));
    itens.push(new Item(id++, "Mutant Bone Boots", "https://www.tibiawiki.com.br/images/5/52/Mutant_Bone_Boots.gif", [VocacaoEnum.Druid], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Death, 3)], 0));
    itens.push(new Item(id++, "Norcferatu Fangstompers", "https://www.tibiawiki.com.br/images/2/2a/Norcferatu_Fangstompers.gif", [VocacaoEnum.Sorcerer], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Death, 3)], 0));
    itens.push(new Item(id++, "Norcferatu Goretrampers", "https://www.tibiawiki.com.br/images/e/ea/Norcferatu_Goretrampers.gif", [VocacaoEnum.Knight], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Physical, 5), new Protecao(ProtecaoEnum.Earth, 5)], 0));
    itens.push(new Item(id++, "Alchemist's Boots", "https://www.tibiawiki.com.br/images/9/9d/Alchemist%27s_Boots.gif", [VocacaoEnum.Sorcerer], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Physical, 2)], 0));
    itens.push(new Item(id++, "Stoic Iks Boots", "https://www.tibiawiki.com.br/images/9/9c/Stoic_Iks_Boots.gif", [VocacaoEnum.Paladin], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Fire, 5)], 0));
    itens.push(new Item(id++, "Stoic Iks Sandals", "https://www.tibiawiki.com.br/images/4/4b/Stoic_Iks_Sandals.gif", [VocacaoEnum.Sorcerer], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Ice, 6)], 0));
    itens.push(new Item(id++, "Cobra Boots", "https://www.tibiawiki.com.br/images/9/9e/Cobra_Boots.gif", [VocacaoEnum.Knight], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Physical, 6)], 0));
    itens.push(new Item(id++, "Winged Boots", "https://www.tibiawiki.com.br/images/a/ac/Winged_Boots.gif", [VocacaoEnum.Paladin], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Earth, 7)], 0));
    itens.push(new Item(id++, "Pair of Dreamwalkers", "https://www.tibiawiki.com.br/images/5/53/Pair_of_Dreamwalkers.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Earth, 8)], 0));
    itens.push(new Item(id++, "Make-do Boots", "https://www.tibiawiki.com.br/images/4/43/Make-do_Boots.gif", [VocacaoEnum.Druid], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Ice, 6)], 0));
    itens.push(new Item(id++, "Depth Calcei", "https://www.tibiawiki.com.br/images/e/e7/Depth_Calcei.gif", [VocacaoEnum.Knight], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Physical, 5)], 0));
    itens.push(new Item(id++, "Prismatic Boots", "https://www.tibiawiki.com.br/images/7/7f/Prismatic_Boots.gif", [VocacaoEnum.Paladin], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Death, 3)], 0));
    itens.push(new Item(id++, "Makeshift Boots", "https://www.tibiawiki.com.br/images/1/1b/Makeshift_Boots.gif", [VocacaoEnum.Sorcerer], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Fire, 8)], 0));
    itens.push(new Item(id++, "Guardian Boots", "https://www.tibiawiki.com.br/images/1/17/Guardian_Boots.gif", [VocacaoEnum.Knight, VocacaoEnum.Paladin], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Physical, 2), new Protecao(ProtecaoEnum.Holy, -2)], 0));
    itens.push(new Item(id++, "Pair of Nightmare Boots", "https://www.tibiawiki.com.br/images/e/ec/Pair_of_Nightmare_Boots.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Energy, 6)], 0));
    itens.push(new Item(id++, "Void Boots", "https://www.tibiawiki.com.br/images/f/f7/Void_Boots.gif", this.allVocations(), SlotEnum.Boots, 0, false, [new Protecao(ProtecaoEnum.Energy, 10)], 0));

    // Shields
    itens.push(new Item(id++, "Soulbastion", "https://www.tibiawiki.com.br/images/b/bd/Soulbastion.gif", [VocacaoEnum.Knight], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Physical, 10), new Protecao(ProtecaoEnum.Death, 10)], 1, [ImbuimentProtecaoEnum.Earth, ImbuimentProtecaoEnum.Energy, ImbuimentProtecaoEnum.Fire, ImbuimentProtecaoEnum.Holy, ImbuimentProtecaoEnum.Ice]));
    itens.push(new Item(id++, "Refined Stag Shield", "https://www.tibiawiki.com.br/images/d/d8/Refined_Stag_Shield.gif", [VocacaoEnum.Knight], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Physical, 5), new Protecao(ProtecaoEnum.Ice, 12)], 1, Item.allImbuiments(ImbuimentProtecaoEnum.Ice)));
    itens.push(new Item(id++, "Stag Shield", "https://www.tibiawiki.com.br/images/d/d8/Refined_Stag_Shield.gif", [VocacaoEnum.Knight], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Physical, 5), new Protecao(ProtecaoEnum.Ice, 10)], 1, Item.allImbuiments(ImbuimentProtecaoEnum.Ice)));
    itens.push(new Item(id++, "Falcon Escutcheon", "https://www.tibiawiki.com.br/images/e/ef/Falcon_Escutcheon.gif", [VocacaoEnum.Knight], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Physical, 7), new Protecao(ProtecaoEnum.Fire, 15)], 1, [ImbuimentProtecaoEnum.Death, ImbuimentProtecaoEnum.Earth, ImbuimentProtecaoEnum.Energy, ImbuimentProtecaoEnum.Holy, ImbuimentProtecaoEnum.Ice]));
    itens.push(new Item(id++, "Falcon Shield", "https://www.tibiawiki.com.br/images/2/29/Falcon_Shield.gif", [VocacaoEnum.Knight], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Physical, 6), new Protecao(ProtecaoEnum.Fire, 10)], 1, [ImbuimentProtecaoEnum.Death, ImbuimentProtecaoEnum.Earth, ImbuimentProtecaoEnum.Energy, ImbuimentProtecaoEnum.Holy, ImbuimentProtecaoEnum.Ice]));
    itens.push(new Item(id++, "Eldritch Shield", "https://www.tibiawiki.com.br/images/5/5b/Eldritch_Shield.gif", [VocacaoEnum.Knight], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Physical, 4)], 1, Item.allImbuiments()));
    itens.push(new Item(id++, "Lion Shield", "https://www.tibiawiki.com.br/images/b/bc/Lion_Shield.gif", [VocacaoEnum.Knight], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Physical, 7), new Protecao(ProtecaoEnum.Earth, 10)], 1, [ImbuimentProtecaoEnum.Death, ImbuimentProtecaoEnum.Energy, ImbuimentProtecaoEnum.Fire, ImbuimentProtecaoEnum.Holy, ImbuimentProtecaoEnum.Ice]));
    itens.push(new Item(id++, "Biscuit Barrier", "https://www.tibiawiki.com.br/images/1/12/Biscuit_Barrier.gif", [VocacaoEnum.Knight], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Physical, 3), new Protecao(ProtecaoEnum.Fire, 5), new Protecao(ProtecaoEnum.Ice, -2)], 1, [ImbuimentProtecaoEnum.Death, ImbuimentProtecaoEnum.Earth, ImbuimentProtecaoEnum.Energy, ImbuimentProtecaoEnum.Holy]));
    itens.push(new Item(id++, "Gnome Shield", "https://www.tibiawiki.com.br/images/1/1c/Gnome_Shield.gif", [VocacaoEnum.Knight], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Physical, 6), new Protecao(ProtecaoEnum.Energy, 8), new Protecao(ProtecaoEnum.Ice, -2)], 1, [ImbuimentProtecaoEnum.Death, ImbuimentProtecaoEnum.Earth, ImbuimentProtecaoEnum.Fire, ImbuimentProtecaoEnum.Holy]));
    itens.push(new Item(id++, "Ectoplasmic Shield", "https://www.tibiawiki.com.br/images/7/78/Ectoplasmic_Shield.gif", [VocacaoEnum.Knight], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Ice, 7), new Protecao(ProtecaoEnum.Fire, -3)], 1, [ImbuimentProtecaoEnum.Death, ImbuimentProtecaoEnum.Earth, ImbuimentProtecaoEnum.Energy, ImbuimentProtecaoEnum.Holy]));
    itens.push(new Item(id++, "Ornate Shield", "https://www.tibiawiki.com.br/images/4/41/Ornate_Shield.gif", [VocacaoEnum.Knight], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Physical, 4)], 1, Item.allImbuiments()));
    itens.push(new Item(id++, "Prismatic Shield", "https://www.tibiawiki.com.br/images/b/b7/Prismatic_Shield.gif", [VocacaoEnum.Knight], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Physical, 4)], 0));
    itens.push(new Item(id++, "Mastermind Shield", "https://www.tibiawiki.com.br/images/1/10/Mastermind_Shield.gif", [VocacaoEnum.Knight], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [], 1, Item.allImbuiments()));

    // Quivers
    itens.push(new Item(id++, "Naga Quiver", "https://www.tibiawiki.com.br/images/7/78/Naga_Quiver.gif", [VocacaoEnum.Paladin], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Ice, 2)], 0));
    itens.push(new Item(id++, "Candy-Coated Quiver", "https://www.tibiawiki.com.br/images/9/92/Candy-Coated_Quiver.gif", [VocacaoEnum.Paladin], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Fire, 2)], 0));

    // Spellbooks
    itens.push(new Item(id++, "Arboreal Tome", "https://www.tibiawiki.com.br/images/c/cc/Arboreal_Tome.gif", [VocacaoEnum.Druid], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Physical, 4), new Protecao(ProtecaoEnum.Energy, 6)], 1, [ImbuimentProtecaoEnum.Death, ImbuimentProtecaoEnum.Earth, ImbuimentProtecaoEnum.Fire, ImbuimentProtecaoEnum.Holy, ImbuimentProtecaoEnum.Ice]));
    itens.push(new Item(id++, "Arcanomancer Folio", "https://www.tibiawiki.com.br/images/5/5b/Arcanomancer_Folio.gif", [VocacaoEnum.Sorcerer], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Physical, 3), new Protecao(ProtecaoEnum.Fire, 8)], 1, [ImbuimentProtecaoEnum.Death, ImbuimentProtecaoEnum.Earth, ImbuimentProtecaoEnum.Energy, ImbuimentProtecaoEnum.Holy, ImbuimentProtecaoEnum.Ice]));
    itens.push(new Item(id++, "Stag Scrolls", "https://www.tibiawiki.com.br/wiki/Arquivo:Stag_Scrolls.gif", [VocacaoEnum.Druid], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Physical, 2), new Protecao(ProtecaoEnum.Death, 5)], 1, Item.allImbuiments(ImbuimentProtecaoEnum.Death)));
    itens.push(new Item(id++, "Stag Spellbook", "https://www.tibiawiki.com.br/images/5/52/Stag_Spellbook.gif", [VocacaoEnum.Sorcerer], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Physical, 2), new Protecao(ProtecaoEnum.Energy, 6)], 1, Item.allImbuiments(ImbuimentProtecaoEnum.Energy)));
    itens.push(new Item(id++, "Eldritch Folio", "https://www.tibiawiki.com.br/images/7/75/Eldritch_Folio.gif", [VocacaoEnum.Sorcerer], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Earth, 6)], 1, [ImbuimentProtecaoEnum.Death, ImbuimentProtecaoEnum.Energy, ImbuimentProtecaoEnum.Fire, ImbuimentProtecaoEnum.Holy, ImbuimentProtecaoEnum.Ice]));
    itens.push(new Item(id++, "Eldritch Tome", "https://www.tibiawiki.com.br/images/f/f8/Eldritch_Tome.gif", [VocacaoEnum.Druid], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Fire, 6)], 1, [ImbuimentProtecaoEnum.Death, ImbuimentProtecaoEnum.Earth, ImbuimentProtecaoEnum.Energy, ImbuimentProtecaoEnum.Holy, ImbuimentProtecaoEnum.Ice]));
    itens.push(new Item(id++, "Alchemist's Notepad", "https://www.tibiawiki.com.br/images/2/2d/Alchemist%27s_Notepad.gif", [VocacaoEnum.Sorcerer], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Death, 5)], 1, [ImbuimentProtecaoEnum.Earth, ImbuimentProtecaoEnum.Energy, ImbuimentProtecaoEnum.Fire, ImbuimentProtecaoEnum.Holy, ImbuimentProtecaoEnum.Ice]));
    itens.push(new Item(id++, "Umbral Master Spellbook", "https://www.tibiawiki.com.br/images/9/9c/Umbral_Master_Spellbook.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Earth, 5), new Protecao(ProtecaoEnum.Energy, 5), new Protecao(ProtecaoEnum.Fire, 5), new Protecao(ProtecaoEnum.Ice, 5)], 1, [ImbuimentProtecaoEnum.Death, ImbuimentProtecaoEnum.Holy]));
    itens.push(new Item(id++, "Lion Spellbook", "https://www.tibiawiki.com.br/images/e/eb/Lion_Spellbook.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Physical, 3), new Protecao(ProtecaoEnum.Ice, 7)], 1, [ImbuimentProtecaoEnum.Death, ImbuimentProtecaoEnum.Earth, ImbuimentProtecaoEnum.Energy, ImbuimentProtecaoEnum.Fire, ImbuimentProtecaoEnum.Holy]));
    itens.push(new Item(id++, "Cocoa Grimoire", "https://www.tibiawiki.com.br/images/8/87/Cocoa_Grimoire.gif", [VocacaoEnum.Sorcerer], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Physical, 2), new Protecao(ProtecaoEnum.Energy, 5)], 1, Item.allImbuiments(ImbuimentProtecaoEnum.Energy)));
    itens.push(new Item(id++, "Creamy Grimoire", "https://www.tibiawiki.com.br/images/6/62/Creamy_Grimoire.gif", [VocacaoEnum.Druid], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Physical, 2), new Protecao(ProtecaoEnum.Fire, 5)], 1, Item.allImbuiments(ImbuimentProtecaoEnum.Fire)));
    itens.push(new Item(id++, "Brain in a Jar", "https://www.tibiawiki.com.br/images/a/a9/Brain_in_a_Jar.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Earth, 7)], 1, [ImbuimentProtecaoEnum.Death, ImbuimentProtecaoEnum.Energy, ImbuimentProtecaoEnum.Fire, ImbuimentProtecaoEnum.Holy, ImbuimentProtecaoEnum.Ice]));
    itens.push(new Item(id++, "Shoulder Plate", "https://www.tibiawiki.com.br/images/3/32/Shoulder_Plate.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Physical, 3), new Protecao(ProtecaoEnum.Earth, 6)], 1, [ImbuimentProtecaoEnum.Death, ImbuimentProtecaoEnum.Energy, ImbuimentProtecaoEnum.Fire, ImbuimentProtecaoEnum.Holy, ImbuimentProtecaoEnum.Ice]));
    itens.push(new Item(id++, "Spirit Guide", "https://www.tibiawiki.com.br/images/4/42/Spirit_Guide.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Energy, 6)], 1, [ImbuimentProtecaoEnum.Death, ImbuimentProtecaoEnum.Earth, ImbuimentProtecaoEnum.Fire, ImbuimentProtecaoEnum.Holy, ImbuimentProtecaoEnum.Ice]));
    itens.push(new Item(id++, "Spellbook of Ancient Arcana", "https://www.tibiawiki.com.br/images/3/3c/Spellbook_of_Ancient_Arcana.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Death, 5)], 0));
    itens.push(new Item(id++, "Umbral Spellbook", "https://www.tibiawiki.com.br/images/e/e3/Umbral_Spellbook.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Earth, 3), new Protecao(ProtecaoEnum.Energy, 3), new Protecao(ProtecaoEnum.Fire, 3), new Protecao(ProtecaoEnum.Ice, 3)], 1, [ImbuimentProtecaoEnum.Death, ImbuimentProtecaoEnum.Holy]));
    itens.push(new Item(id++, "Spellbook of Vigilance", "https://www.tibiawiki.com.br/images/2/2c/Spellbook_of_Vigilance.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Earth, 3), new Protecao(ProtecaoEnum.Fire, 5)], 0));
    itens.push(new Item(id++, "Wooden Spellbook", "https://www.tibiawiki.com.br/images/0/07/Wooden_Spellbook.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Earth, 5)], 1, [ImbuimentProtecaoEnum.Death, ImbuimentProtecaoEnum.Energy, ImbuimentProtecaoEnum.Fire, ImbuimentProtecaoEnum.Holy, ImbuimentProtecaoEnum.Ice]));
    itens.push(new Item(id++, "Crude Umbral Spellbook", "https://www.tibiawiki.com.br/images/5/50/Crude_Umbral_Spellbook.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.ShieldOrSpellbookOrQuiver, 0, false, [new Protecao(ProtecaoEnum.Earth, 2), new Protecao(ProtecaoEnum.Energy, 2), new Protecao(ProtecaoEnum.Fire, 2), new Protecao(ProtecaoEnum.Ice, 2)], 0));

    // Amulets
    itens.push(new Item(id++, "Enchanted Merudri Brooch", "https://www.tibiawiki.com.br/images/6/62/Enchanted_Merudri_Brooch.gif", [VocacaoEnum.Monk], SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 4), new Protecao(ProtecaoEnum.Fire, 15)], 0));
    itens.push(new Item(id++, "Enchanted Swan Amulet of Balance", "https://www.tibiawiki.com.br/images/5/5d/Enchanted_Swan_Amulet_of_Balance.gif", [VocacaoEnum.Monk], SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 4), new Protecao(ProtecaoEnum.Ice, 12)], 0));
    itens.push(new Item(id++, "Harmony Amulet", "https://www.tibiawiki.com.br/images/1/1c/Harmony_Amulet.gif", [VocacaoEnum.Monk], SlotEnum.Amulet, 0, false, [], 0));
    itens.push(new Item(id++, "Collar of Orange Plasma", "https://www.tibiawiki.com.br/images/e/e7/Collar_of_Orange_Plasma.gif", [VocacaoEnum.Monk], SlotEnum.Amulet, 0, false, [], 0));
    itens.push(new Item(id++, "Enchanted Flamingo Amulet of Valor", "https://www.tibiawiki.com.br/images/4/4c/Enchanted_Flamingo_Amulet_of_Valor.gif", [VocacaoEnum.Knight], SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 7), new Protecao(ProtecaoEnum.Fire, 12)], 0));
    itens.push(new Item(id++, "Enchanted Turtle Amulet", "https://www.tibiawiki.com.br/images/e/ef/Enchanted_Turtle_Amulet.gif", [VocacaoEnum.Knight], SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 7), new Protecao(ProtecaoEnum.Ice, 15)], 0));
    itens.push(new Item(id++, "Collar of Red Plasma", "https://www.tibiawiki.com.br/images/a/ae/Collar_of_Red_Plasma.gif", [VocacaoEnum.Knight], SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 5)], 0));
    itens.push(new Item(id++, "Enchanted Flamingo Amulet of Precision", "https://www.tibiawiki.com.br/images/7/71/Enchanted_Flamingo_Amulet_of_Precision.gif", [VocacaoEnum.Paladin], SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 5), new Protecao(ProtecaoEnum.Fire, 14)], 0));
    itens.push(new Item(id++, "Enchanted Pendulet", "https://www.tibiawiki.com.br/images/1/1c/Enchanted_Pendulet.gif", [VocacaoEnum.Paladin], SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 5), new Protecao(ProtecaoEnum.Energy, 18)], 0));
    itens.push(new Item(id++, "Enchanted Flamingo Amulet of Destruction", "https://www.tibiawiki.com.br/images/1/1a/Enchanted_Flamingo_Amulet_of_Destruction.gif", [VocacaoEnum.Sorcerer], SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 3), new Protecao(ProtecaoEnum.Fire, 11)], 0));
    itens.push(new Item(id++, "Enchanted Flamingo Amulet of Nature", "https://www.tibiawiki.com.br/images/e/e8/Enchanted_Flamingo_Amulet_of_Nature.gif", [VocacaoEnum.Druid], SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 3), new Protecao(ProtecaoEnum.Fire, 11)], 0));
    itens.push(new Item(id++, "Enchanted Sleep Shawl", "https://www.tibiawiki.com.br/images/6/66/Enchanted_Sleep_Shawl.gif", [VocacaoEnum.Paladin], SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 7), new Protecao(ProtecaoEnum.Earth, 24)], 0));
    itens.push(new Item(id++, "Enchanted Theurgic Amulet", "https://www.tibiawiki.com.br/images/8/8d/Enchanted_Theurgic_Amulet.gif", [VocacaoEnum.Druid, VocacaoEnum.Sorcerer], SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 3), new Protecao(ProtecaoEnum.Earth, 14)], 0));
    itens.push(new Item(id++, "The Cobra Amulet", "https://www.tibiawiki.com.br/images/5/57/The_Cobra_Amulet.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Death, 9)], 0));
    itens.push(new Item(id++, "Lion Amulet", "https://www.tibiawiki.com.br/images/2/21/Lion_Amulet.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 3), new Protecao(ProtecaoEnum.Ice, 7)], 0));
    itens.push(new Item(id++, "Candy Necklace", "https://www.tibiawiki.com.br/images/0/0d/Candy_Necklace.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 3), new Protecao(ProtecaoEnum.Energy, 6), new Protecao(ProtecaoEnum.Earth, -5)], 0));
    itens.push(new Item(id++, "Rainbow Necklace", "https://www.tibiawiki.com.br/images/d/d8/Rainbow_Necklace.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 3), new Protecao(ProtecaoEnum.Fire, 6), new Protecao(ProtecaoEnum.Ice, -5)], 0));
    itens.push(new Item(id++, "Exotic Amulet", "https://www.tibiawiki.com.br/images/e/ef/Exotic_Amulet.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 4), new Protecao(ProtecaoEnum.Earth, 5)], 0));
    itens.push(new Item(id++, "Gill Necklace", "https://www.tibiawiki.com.br/images/1/18/Gill_Necklace.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 15), new Protecao(ProtecaoEnum.Earth, 10)], 0));
    itens.push(new Item(id++, "Prismatic Necklace", "https://www.tibiawiki.com.br/images/b/b4/Prismatic_Necklace.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 10), new Protecao(ProtecaoEnum.Energy, 15)], 0));
    itens.push(new Item(id++, "Necklace of the Deep", "https://www.tibiawiki.com.br/images/0/06/Necklace_of_the_Deep.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.LifeDrain, 50)], 0));
    itens.push(new Item(id++, "Foxtail Amulet", "https://www.tibiawiki.com.br/images/a/a9/Foxtail_Amulet.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 5)], 0));
    itens.push(new Item(id++, "Bonfire Amulet", "https://www.tibiawiki.com.br/images/3/3f/Bonfire_Amulet.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 60), new Protecao(ProtecaoEnum.Fire, 40)], 0));
    itens.push(new Item(id++, "Leviathan's Amulet", "https://www.tibiawiki.com.br/images/d/d3/Leviathan%27s_Amulet.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 60), new Protecao(ProtecaoEnum.Ice, 40)], 0));
    itens.push(new Item(id++, "Sacred Tree Amulet", "https://www.tibiawiki.com.br/images/1/16/Sacred_Tree_Amulet.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 60), new Protecao(ProtecaoEnum.Earth, 40)], 0));
    itens.push(new Item(id++, "Shockwave Amulet", "https://www.tibiawiki.com.br/images/4/41/Shockwave_Amulet.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 60), new Protecao(ProtecaoEnum.Energy, 40)], 0));
    itens.push(new Item(id++, "Glacier Amulet", "https://www.tibiawiki.com.br/images/d/d6/Glacier_Amulet.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Ice, 20), new Protecao(ProtecaoEnum.Energy, -10)], 0));
    itens.push(new Item(id++, "Lightning Pendant", "https://www.tibiawiki.com.br/images/3/35/Lightning_Pendant.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Energy, 20), new Protecao(ProtecaoEnum.Earth, -10)], 0));
    itens.push(new Item(id++, "Magma Amulet", "https://www.tibiawiki.com.br/images/3/31/Magma_Amulet.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Fire, 20), new Protecao(ProtecaoEnum.Ice, -10)], 0));
    itens.push(new Item(id++, "Terra Amulet", "https://www.tibiawiki.com.br/images/e/ed/Terra_Amulet.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Earth, 20), new Protecao(ProtecaoEnum.Fire, -10)], 0));
    itens.push(new Item(id++, "Onyx Pendant", "https://www.tibiawiki.com.br/images/2/27/Onyx_Pendant.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Death, 2)], 0));
    itens.push(new Item(id++, "Bronze Amulet", "https://www.tibiawiki.com.br/images/e/ee/Bronze_Amulet.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.ManaDrain, 20)], 0));
    itens.push(new Item(id++, "Dragon Necklace", "https://www.tibiawiki.com.br/images/b/b0/Dragon_Necklace.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Fire, 8)], 0));
    itens.push(new Item(id++, "Enchanted Werewolf Amulet", "https://www.tibiawiki.com.br/images/7/7e/Enchanted_Werewolf_Amulet.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 6)], 0));
    itens.push(new Item(id++, "Garlic Necklace", "https://www.tibiawiki.com.br/images/1/16/Garlic_Necklace.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.LifeDrain, 20)], 0));
    itens.push(new Item(id++, "Koshei's Ancient Amulet", "https://www.tibiawiki.com.br/images/5/5a/Koshei%27s_Ancient_Amulet.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Death, 8), new Protecao(ProtecaoEnum.Holy, -50)], 0));
    itens.push(new Item(id++, "Protection Amulet", "https://www.tibiawiki.com.br/images/3/38/Protection_Amulet.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 6)], 0));
    itens.push(new Item(id++, "Silver Amulet", "https://www.tibiawiki.com.br/images/1/18/Silver_Amulet.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Earth, 10)], 0));
    itens.push(new Item(id++, "Strange Talisman", "https://www.tibiawiki.com.br/images/6/66/Strange_Talisman.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Energy, 10)], 0));
    itens.push(new Item(id++, "Elven Amulet", "https://www.tibiawiki.com.br/images/f/f1/Elven_Amulet.gif", this.allVocations(), SlotEnum.Amulet, 0, false, [new Protecao(ProtecaoEnum.Physical, 5), new Protecao(ProtecaoEnum.Fire, 5), new Protecao(ProtecaoEnum.Earth, 5), new Protecao(ProtecaoEnum.Energy, 5), new Protecao(ProtecaoEnum.Ice, 5), new Protecao(ProtecaoEnum.Holy, 5), new Protecao(ProtecaoEnum.Death, 5)], 0));

    // Rings
    itens.push(new Item(id++, "Charged Ethereal Ring", "https://www.tibiawiki.com.br/images/2/22/Charged_Ethereal_Ring.gif", [VocacaoEnum.Monk], SlotEnum.Ring, 0, false, [new Protecao(ProtecaoEnum.Physical, 4), new Protecao(ProtecaoEnum.Fire, 4), new Protecao(ProtecaoEnum.Earth, 4), new Protecao(ProtecaoEnum.Energy, 4), new Protecao(ProtecaoEnum.Ice, 4)], 0));
    itens.push(new Item(id++, "Arboreal Ring", "https://www.tibiawiki.com.br/images/3/34/Charged_Arboreal_Ring.gif", [VocacaoEnum.Druid], SlotEnum.Ring, 0, false, [new Protecao(ProtecaoEnum.Fire, 4), new Protecao(ProtecaoEnum.Earth, 4), new Protecao(ProtecaoEnum.Energy, 4), new Protecao(ProtecaoEnum.Ice, 4)], 0));
    itens.push(new Item(id++, "Spiritthorn Ring", "https://www.tibiawiki.com.br/images/7/75/Charged_Spiritthorn_Ring.gif", [VocacaoEnum.Knight], SlotEnum.Ring, 0, false, [new Protecao(ProtecaoEnum.Physical, 8), new Protecao(ProtecaoEnum.Fire, 4), new Protecao(ProtecaoEnum.Earth, 4), new Protecao(ProtecaoEnum.Energy, 4), new Protecao(ProtecaoEnum.Ice, 4)], 0));
    itens.push(new Item(id++, "Alicorn Ring", "https://www.tibiawiki.com.br/images/6/63/Charged_Alicorn_Ring.gif", [VocacaoEnum.Paladin], SlotEnum.Ring, 0, false, [new Protecao(ProtecaoEnum.Fire, 4), new Protecao(ProtecaoEnum.Earth, 4), new Protecao(ProtecaoEnum.Energy, 4), new Protecao(ProtecaoEnum.Ice, 4), new Protecao(ProtecaoEnum.Holy, 4), new Protecao(ProtecaoEnum.Death, 4)], 0));
    itens.push(new Item(id++, "Arcanomancer Sigil", "https://www.tibiawiki.com.br/images/7/77/Charged_Arcanomancer_Sigil.gif", [VocacaoEnum.Sorcerer], SlotEnum.Ring, 0, false, [new Protecao(ProtecaoEnum.Fire, 4), new Protecao(ProtecaoEnum.Earth, 4), new Protecao(ProtecaoEnum.Energy, 4), new Protecao(ProtecaoEnum.Ice, 4)], 0));
    itens.push(new Item(id++, "Ring of Red Plasma", "https://www.tibiawiki.com.br/images/c/cb/Ring_of_Red_Plasma.gif", [VocacaoEnum.Knight], SlotEnum.Ring, 0, false, [new Protecao(ProtecaoEnum.Physical, 3)], 0));
    itens.push(new Item(id++, "Enchanted Blister Ring", "https://www.tibiawiki.com.br/images/d/d0/Enchanted_Blister_Ring.gif", this.allVocations(), SlotEnum.Ring, 0, false, [new Protecao(ProtecaoEnum.Fire, 6)], 0));
    itens.push(new Item(id++, "Enchanted Ring of Souls", "https://www.tibiawiki.com.br/images/5/55/Enchanted_Ring_of_Souls.gif", this.allVocations(), SlotEnum.Ring, 0, false, [new Protecao(ProtecaoEnum.Physical, 2), new Protecao(ProtecaoEnum.LifeDrain, 10)], 0));
    itens.push(new Item(id++, "Prismatic Ring", "https://www.tibiawiki.com.br/images/c/cb/Prismatic_Ring.gif", this.allVocations(), SlotEnum.Ring, 0, false, [new Protecao(ProtecaoEnum.Physical, 10), new Protecao(ProtecaoEnum.Energy, 8)], 0));
    itens.push(new Item(id++, "Butterfly Ring", "https://www.tibiawiki.com.br/images/b/b1/Butterfly_Ring.gif", this.allVocations(), SlotEnum.Ring, 0, false, [new Protecao(ProtecaoEnum.Death, 3)], 0));

    // Extra Slots
    itens.push(new Item(id++, "Ink Quill", "https://www.tibiawiki.com.br/images/4/47/Ink_Quill.gif", [VocacaoEnum.Paladin], SlotEnum.ExtraSlot, 0, false, [new Protecao(ProtecaoEnum.Energy, 2)], 0));
    itens.push(new Item(id++, "Ink Claw", "https://www.tibiawiki.com.br/images/b/b1/Ink_Claw.gif", [VocacaoEnum.Sorcerer], SlotEnum.ExtraSlot, 0, false, [new Protecao(ProtecaoEnum.Energy, 2)], 0));
    itens.push(new Item(id++, "Ink Brush", "https://www.tibiawiki.com.br/images/e/e7/Ink_Brush.gif", [VocacaoEnum.Monk], SlotEnum.ExtraSlot, 0, false, [new Protecao(ProtecaoEnum.Energy, 2)], 0));
    itens.push(new Item(id++, "Ink Blade", "https://www.tibiawiki.com.br/images/9/9c/Ink_Blade.gif", [VocacaoEnum.Knight], SlotEnum.ExtraSlot, 0, false, [new Protecao(ProtecaoEnum.Energy, 2)], 0));
    itens.push(new Item(id++, "Ink Vine", "https://www.tibiawiki.com.br/images/3/3a/Ink_Vine.gif", [VocacaoEnum.Druid], SlotEnum.ExtraSlot, 0, false, [new Protecao(ProtecaoEnum.Energy, 2)], 0));
    itens.push(new Item(id++, "Sun Catcher", "https://www.tibiawiki.com.br/images/d/da/Sun_Catcher.gif", this.allVocations(), SlotEnum.ExtraSlot, 0, false, [new Protecao(ProtecaoEnum.Fire, 5)], 0));
    itens.push(new Item(id++, "Moon Mirror", "https://www.tibiawiki.com.br/images/4/46/Moon_Mirror.gif", this.allVocations(), SlotEnum.ExtraSlot, 0, false, [new Protecao(ProtecaoEnum.Death, 5)], 0));
    itens.push(new Item(id++, "Starlight Vial", "https://www.tibiawiki.com.br/images/9/99/Starlight_Vial.gif", this.allVocations(), SlotEnum.ExtraSlot, 0, false, [new Protecao(ProtecaoEnum.ManaDrain, 5)], 0));
    itens.push(new Item(id++, "Lit Torch", "https://www.tibiawiki.com.br/images/3/3a/Lit_Torch.gif", this.allVocations(), SlotEnum.ExtraSlot, 0, false, [new Protecao(ProtecaoEnum.Holy, 2)], 0));
    itens.push(new Item(id++, "Bone Fiddle", "https://www.tibiawiki.com.br/images/3/3b/Bone_Fiddle.gif", this.allVocations(), SlotEnum.ExtraSlot, 0, false, [new Protecao(ProtecaoEnum.LifeDrain, 5)], 0));
    itens.push(new Item(id++, "Conch Shell Horn", "https://www.tibiawiki.com.br/images/5/5b/Conch_Shell_Horn.gif", this.allVocations(), SlotEnum.ExtraSlot, 0, false, [new Protecao(ProtecaoEnum.Ice, 2)], 0));
    itens.push(new Item(id++, "Scarab Ocarina", "https://www.tibiawiki.com.br/images/b/be/Scarab_Ocarina.gif", this.allVocations(), SlotEnum.ExtraSlot, 0, false, [new Protecao(ProtecaoEnum.Earth, 2)], 0));

    return itens;
  }

  static allVocations(): VocacaoEnum[] {
    return [VocacaoEnum.Knight, VocacaoEnum.Paladin, VocacaoEnum.Druid, VocacaoEnum.Sorcerer, VocacaoEnum.Monk]
  }
}

